import { themeTokens } from "@/lib/theme/tokens";

export const homeContent = {
  hero: {
    badge: "INFRASTRUCTURE - NOT A SERVICE",
    title: "We route high-intent introductions.",
    subtitle: "Private introductions when timing and fit already align.",
    cta: "Access the Routing Layer",
  },
  infrastructureBadge: {
    text: "Infrastructure - Not a Service",
    uiFont: "Inter",
    bg: "transparent",
    border: "rgba(255,184,0,0.35)",
    textColor: "rgba(255,255,255,0.92)",
    dotColor: "#FFB800",
    maxWidth: 740,
    paddingY: 0,
    radius: 18,
  },
  throughputStrip: {
    pill: "THROUGHPUT CAPACITY",
    value1: "2.4k",
    suffix1: "/day",
    label1: "Signals Processed",
    value2: "87",
    suffix2: "%",
    label2: "Qualification Rate",
    value3: "<120",
    suffix3: "ms",
    label3: "Avg Route Time",
    headingFont: "Clash Grotesk",
    uiFont: "Inter",
    bodyFont: "Inter",
    bg: "transparent",
    panelBg: "rgba(6, 12, 14, 0.92)",
    border: "rgba(0,255,200,0.24)",
    text: "rgba(230,230,230,0.96)",
    muted: "rgba(255,255,255,0.52)",
    accent1: "#00D7A8",
    accent2: "#16C3FF",
    accent3: "#5EA8FF",
    maxWidth: 1120,
    paddingY: 8,
    radius: 14,
  },
  connectIdealClients: {
    eyebrow: "THE ROUTING LAYER",
    heading: "Connect with Your Ideal Clients",
    subheading:
      "B2B executives and business owners partner with myoProcess to get connected directly with their ideal client profile through our intelligent routing infrastructure.",
    items: [
      {
        index: "01",
        title: "Signal Layer",
        description: "Incoming buyer signals, intent data, and qualification triggers.",
      },
      {
        index: "02",
        title: "Routing Layer",
        description: "Real-time matching, qualification filtering, and pathway control.",
      },
      {
        index: "03",
        title: "Connection Layer",
        description: "Executed routes, completed handoffs, and transaction flow.",
      },
    ],
    footnote:
      "Your ideal clients, delivered. Every qualified signal, every matched connection, every introduction routed directly to you through myoProcess.",
  },
  systemLevelProcessing: {
    eyebrow: "THE PROTOCOL",
    heading: "System-Level Processing",
    subheading: "Not steps. Not tasks. A continuous flow of signal processing at infrastructure scale.",
    cards: [
      {
        stage: "DETECT",
        title: "Signal Detection",
        description: "Inbound buyer signals enter the system",
        metrics: ["Signal Volume", "Intent Strength", "Source Quality"],
        tone: "teal",
      },
      {
        stage: "QUALIFY",
        title: "Route Qualification",
        description: "Real-time filtering and pathway validation",
        metrics: ["Match Score", "Qualification Rate", "Filter Efficiency"],
        tone: "blue",
      },
      {
        stage: "ROUTE",
        title: "Pathway Execution",
        description: "Controlled connection to optimal destination",
        metrics: ["Routing Speed", "Path Accuracy", "Throughput"],
        tone: "green",
      },
      {
        stage: "COMPLETE",
        title: "Transaction Flow",
        description: "Successful handoff and outcome tracking",
        metrics: ["Completion Rate", "Transaction Value", "Network Effect"],
        tone: "green",
      },
    ],
  },
  twoSidedNetwork: {
    eyebrow: "NETWORK ARCHITECTURE",
    heading: "Two-Sided Routing Network",
    subheading:
      "Compatible nodes connect through the routing layer. Incompatible signals are filtered at the edge.",
    footnote:
      "Network effects compound as node density increases. Each compatible connection strengthens the routing layer. Incompatible signals are rejected before consuming system resources.",
    headingFont: "Clash Grotesk",
    uiFont: "Inter",
    bodyFont: "Inter",
    bg: "transparent",
    panelBg: "rgba(10, 14, 16, 0.62)",
    panelBg2: "rgba(10, 14, 16, 0.72)",
    border: "rgba(0, 255, 200, 0.18)",
    borderStrong: "rgba(0, 255, 200, 0.22)",
    text: "rgba(255,255,255,0.95)",
    muted: "rgba(255,255,255,0.62)",
    accent: "#00FFC8",
    danger: "#FF5252",
    maxWidth: 1120,
    paddingY: 90,
    gap: 44,
    radius: 16,
  },
  oldVsNew: {
    eyebrow: "TRADITIONAL METHODS VS. ROUTING INFRASTRUCTURE",
    heading: "Old Way vs. New Way",
    subheading:
      "Traditional methods make you search. Infrastructure brings them to you.",
    shiftTag: "THE FUNDAMENTAL SHIFT",
    shiftText:
      "Banks don't facilitate transactions, they route capital. Telecoms don't connect calls, they route data. B2B companies don't search for ICP, their ICP routes through them.",
    headingFont: "Clash Grotesk",
    uiFont: "Inter",
    bodyFont: "Inter",
    bg: "transparent",
    text: "rgba(224,224,224,0.95)",
    muted: "rgba(255,255,255,0.62)",
    accent: "#00FFC8",
    panelBg: "rgba(10,14,16,0.62)",
    panelBgStrong: "rgba(10,14,16,0.72)",
    border: "rgba(0,255,200,0.18)",
    borderStrong: "rgba(0,255,200,0.24)",
    maxWidth: 1120,
    paddingY: 86,
    radius: 16,
  },
  accessRouting: {
    eyebrow: "JOIN THE NETWORK",
    heading: "Access the Routing Layer",
    subheading:
      "Network capacity is controlled to maintain signal quality and routing velocity.",
    stat1Label: "ACTIVE ROUTES",
    stat1Value: "2.4k/day",
    stat2Label: "NETWORK CAPACITY",
    stat2Value: "87%",
    stat3Label: "CURRENT NODES",
    stat3Value: "450+",
    infoTitle: "Network access is controlled.",
    infoBody:
      "We maintain strict qualification standards to protect routing integrity. Both buyer and seller nodes must meet network compatibility requirements.\n\nIf your signals are high-quality and your intent is clear, request access to join the routing layer.",
    headingFont: "Clash Grotesk",
    uiFont: "Inter",
    bodyFont: "Inter",
    bg: "transparent",
    text: "rgba(224,224,224,0.95)",
    muted: "rgba(255,255,255,0.62)",
    accent: "#00FFC8",
    panelBg: "rgba(10,14,16,0.62)",
    panelBgStrong: "rgba(10,14,16,0.72)",
    border: "rgba(0,255,200,0.18)",
    borderStrong: "rgba(0,255,200,0.24)",
    maxWidth: 1120,
    paddingY: 90,
    radius: 14,
  },
  testimonial: {
    eyebrow: "Clients & partners",
    title: "We've Helped Hundreds of Partners Globally",
    subtitle: "We've helped hundreds of partners globally, to achieve their goals.",
    quote:
      '"The Cyberg template transformed our website with its modern design and speed. Highly recommend!"',
    author: "John smith",
    role: "Redwood Tech",
  },
  footer: {
    brand: "Westmark Office",
    tagline: "Connecting B2B executives with their ideal clients",
    copyright: "©2026 Westmark Office. All rights reserved",
  },
  theme: themeTokens,
};
